services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - "9020:8080"
    command: start-dev --import-realm
    depends_on:
      keycloak-db:
        condition: service_healthy

  keycloak-db:
    image: postgres:13.16
    ports:
      - "5530:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  keycloak_data:

